---
title: "Datathon"
output: pdf_document
---

```{r, include = FALSE}
library(tidyverse)
library(tidymodels)
library(knitr)
library(dplyr)
library(kableExtra)
library(readr)
library(vip)
library(corrplot)
library(ggplot2)
library(gridExtra)
library(tidytext)
library(tibble)

library(stringr)
library(readxl)
library(writexl)
library(janitor)

tidymodels_prefer()

set.seed(9950)
```

```{r, warning=FALSE}
Permit = read_excel("APR_Download_2024.xlsx")
Affordability = read_excel("Affordability.xlsx")
```

```{r}
Affordability_Cleaning = Affordability %>%
  mutate(
    Jurisdiction = Place %>%
      str_remove(" CDP, California") %>%
      str_remove(" city, California") %>%
      str_remove(" CCD") %>%
      str_remove("-Santa Ynez CCD") %>%
      toupper()
  )

Affordability_Clean = Affordability_Cleaning %>%
  filter(Jurisdiction %in% c("BALLARD", "BUELLTON", "CARPINTERIA", "CASMALIA", "GOLETA", "GUADALUPE", "LOMPOC", "SANTA BARBARA", "SANTA BARBARA COUNTY", "SANTA MARIA", "SOLVANG"))
```

```{r}
AffordabilitySummary = Affordability_Clean %>%
  group_by(Jurisdiction, Year) %>%
  summarise(
    `Total Cost Burden (Renter)` = mean( sum(`Cost Burden >30% (Renter)`, na.rm = TRUE), sum(`Cost Burden >50% (Renter)`, na.rm = TRUE) ),
#    `Total Cost Burden > 50% (Renter)` = sum(`Cost Burden >50% (Renter)`, na.rm = TRUE),
    `Total Cost Burden (Owner)` = mean( sum(`Cost Burden >30% (Owner)`, na.rm = TRUE), sum(`Cost Burden >50% (Owner)`, na.rm = TRUE) ),
#    `Total Cost Burden > 50% (Owner)` = sum(`Cost Burden >50% (Owner)`, na.rm = TRUE),
    `Percent Avg Burdened` = mean( mean(`% Cost Burdened Owners`, na.rm = TRUE), mean(`% Severely Rent Burdened`, na.rm = TRUE) ),
  ) %>%
  ungroup()
```

```{r, warning = FALSE}
Permit$`Above Moderate Income Cert. of Occupancy`
Permit_clean <- Permit %>%
  mutate(
    `Year` = as.numeric(`Year`),
    
    `Very Low Income Cert. of Occupancy` = as.numeric(`Very Low Income Cert. of Occupancy`),
    `Low Income Cert. of Occupancy` = as.numeric(`Low Income Cert. of Occupancy`),
    `Moderate Income Cert. of Occupancy` = as.numeric(`Moderate Income Cert. of Occupancy`),
    
    `Total Entitlements` = as.numeric(`Total Entitlements`),
    `Total Number of Building Permits` = as.numeric(`Total Number of Building Permits`),
    `Total Number of Units Issued Cert. of Occupancy` = as.numeric(`Total Number of Units Issued Cert. of Occupancy`)
  )
Permit_clean <- Permit_clean %>% clean_names()

Permit_clean <- Permit_clean %>%
  mutate(
    `above_moderate_income_cert_of_occupancy` = as.numeric(`above_moderate_income_cert_of_occupancy`)
  )
```

```{r}
Permit_Filtered = Permit_clean %>%
  filter(year %in% c(2017, 2018, 2019, 2020, 2021))

Permit_Total_Summary_Cert <- Permit_Filtered %>%
  group_by(jurisdiction, year) %>%
  summarise(
    `Total Very Low Income Cert. of Occupancy` = sum(`very_low_income_cert_of_occupancy`, na.rm = TRUE),
    `Total Low Income Cert. of Occupancy` = sum(`low_income_cert_of_occupancy`, na.rm = TRUE),
    `Total Moderate Income Cert. of Occupancy` = sum(`moderate_income_cert_of_occupancy`, na.rm = TRUE),
    `Total Above Moderate Income Cert. of Occupancy` = sum(`above_moderate_income_cert_of_occupancy`, na.rm = TRUE)
  ) %>%
  ungroup()
```


```{r, eval = FALSE}
Permit_Total_Summary <- Permit_clean %>%
  group_by(Jurisdiction) %>%
  summarise(
    `Overall Total Entitlements` = sum(`Total Entitlements`, na.rm = TRUE),
    `Overall Total Number of Building Permits` = sum(`Total Number of Building Permits`, na.rm = TRUE),
    `Overall Total Number of Units Issued Cert. of Occupancy` = sum(`Total Number of Units Issued Cert. of Occupancy`, na.rm = TRUE)
  ) %>%
  ungroup()
```

```{r, eval = FALSE}
Permit_Summary <- Permit_Filtered %>%
  group_by(Jurisdiction, Year) %>%
  summarise(
    `Total Low Income Building Permits` = sum(`Low Income Building Permits`, na.rm = TRUE),
    `Total Moderate Income Building Permits` = sum(`Moderate Income Building Permits`, na.rm = TRUE),
    `Total Above Moderate Income Building Permits` = sum(`Above Moderate Income Building Permits`, na.rm = TRUE),
    `Overall Total Entitlements` = sum(`Total Entitlements`, na.rm = TRUE),
    `Overall Total Number of Building Permits` = sum(`Total Number of Building Permits`, na.rm = TRUE),
    `Overall Total Number of Units Issued Cert. of Occupancy` = sum(`Total Number of Units Issued Cert. of Occupancy`, na.rm = TRUE)
  ) %>%
  ungroup()

Permit_Summary
```


```{r}
Permit_Total_Summary_Cert <- Permit_Total_Summary_Cert %>% clean_names()
AffordabilitySummary <- AffordabilitySummary %>% clean_names()
```

```{r}
Data_Final = merge(Permit_Total_Summary_Cert, AffordabilitySummary, id = c("jurisdiction", "year"))
```

```{r}
write_xlsx(x = Data_Final, path = "Combined_Data_Final.xlsx")
```

```{r}
#######################     TRAINING TIME     ###############################

split = initial_split(Data_Final, prop = 0.75)
train_data = training(split)
test_data = testing(split)
```


```{r}
numeric_vars = train_data %>%
  select(where(is.numeric)) %>%
  select(-year)

library(ggcorrplot)
cor_matrix <- cor(numeric_vars)
ggcorrplot(cor_matrix, 
           hc.order = TRUE,    # Reorders variables to show clusters
           type = "lower",     # Shows only the bottom half (removes duplicates)
           lab = TRUE,         # Adds the correlation numbers to the squares
           title = "Correlation of Housing Permit Data")

```

```{r, eval = FALSE}
folds = vfold_cv(train_data, v = 10)


# ENGINE: GLMNET / MODE: REGRESSION

ridge_recipe = recipe(percent_avg_burdened ~ total_very_low_income_cert_of_occupancy + 
                        total_low_income_cert_of_occupancy + 
                        total_moderate_income_cert_of_occupancy +
                        total_above_moderate_income_cert_of_occupancy +
                        total_cost_burden_renter +
                        total_cost_burden_owner
                      , data = train_data) %>%
  step_normalize(all_predictors())


# WORKFLOW: RIDGE REGRESSION (mixture = 0)

ridge_spec = linear_reg(penalty = tune(), mixture = 0) %>%
  set_engine("glmnet")

ridge_workflow = workflow() %>%
  add_recipe(ridge_recipe) %>%
  add_model(ridge_spec)

penalty_grid = grid_regular(penalty(range = c(-5, 5)), levels = 50)

ridge_tuned = tune_grid(
  ridge_workflow,
  resamples = folds,
  grid = penalty_grid,
  metrics = metric_set(rmse)
)

write_rds(ridge_tuned, "data/tuned_models/ridge.rds")


# WORKFLOW: LASSO REGRESSION (mixture = 1)

lasso_spec = linear_reg(penalty = tune(), mixture = 1) %>%
  set_engine("glmnet")

lasso_workflow = workflow() %>%
  add_recipe(ridge_recipe) %>%
  add_model(lasso_spec)

penalty_grid = grid_regular(penalty(range = c(-5, 5)), levels = 50)

lasso_tuned = tune_grid(
  lasso_workflow,
  resamples = folds,
  grid = penalty_grid,
  metrics = metric_set(rmse)
)

write_rds(lasso_tuned, "data/tuned_models/lasso.rds")


# WORKFLOW: ELASTIC NET (mixture in [0, 1])

elastic_spec = linear_reg(penalty = tune(), mixture = tune()) %>%
  set_engine("glmnet")

elastic_workflow = workflow() %>%
  add_recipe(ridge_recipe) %>%
  add_model(elastic_spec)

elastic_grid = grid_regular(penalty(range = c(-5, 5)), mixture(range = c(0,1)), levels = 10)

elastic_tuned = tune_grid(
  elastic_workflow,
  resamples = folds,
  grid = elastic_grid,
  metrics = metric_set(rmse)
)

write_rds(elastic_tuned, "data/tuned_models/elastic.rds")


# ENGINE: KKNN / MODE: REGRESSION

knn_spec = nearest_neighbor(neighbors = tune()) %>%
  set_engine("kknn") %>%
  set_mode("regression")

knn_workflow = workflow() %>%
  add_recipe(ridge_recipe) %>%
  add_model(knn_spec)

knn_grid = grid_regular(neighbors(range = c(1, 20)), levels = 20)

knn_tuned = tune_grid(
  knn_workflow,
  resamples = folds,
  grid = knn_grid
)

write_rds(knn_tuned, "data/tuned_models/knn.rds")


# ENGINE: RANGER / MODE: REGRESSION

rf_spec = rand_forest(mtry = tune(),
  trees = tune(),
  min_n = tune()
) %>%
  set_engine("ranger") %>%
  set_mode("regression")

rf_workflow = workflow() %>%
  add_recipe(ridge_recipe) %>%
  add_model(rf_spec)

rf_grid = grid_regular(mtry(range = c(1, 3)), 
             trees(range = c(100,500)), 
             min_n(range = c(5,20)), 
             levels = 5)

rf_tuned = tune_grid(
  rf_workflow,
  resamples = folds,
  grid = rf_grid
)

write_rds(rf_tuned, "data/tuned_models/rf.rds")


# ENGINE: XGBOOST / MODE: REGRESSION

boost_spec = boost_tree(
  trees = tune(),
  learn_rate = tune(),
  min_n = tune()
) %>%
  set_engine("xgboost") %>%
  set_mode("regression")

boost_workflow = workflow() %>%
  add_recipe(ridge_recipe) %>%
  add_model(boost_spec)

boost_grid = grid_regular(
  trees(range = c(100, 500)),
  learn_rate(range = c(0.01, 0.3)),
  min_n(range = c(2, 20)),
  levels = 5
)

boost_tuned = tune_grid(
  boost_workflow,
  resamples = folds,
  grid = boost_grid
)

write_rds(boost_tuned, "data/tuned_models/boosted.rds")

```

```{r}
ridge_tuned = read_rds("data/tuned_models/ridge.rds")
lasso_tuned = read_rds("data/tuned_models/lasso.rds")
knn_tuned = read_rds("data/tuned_models/knn.rds")
elastic_tuned = read_rds("data/tuned_models/elastic.rds")
rf_tuned = read_rds("data/tuned_models/rf.rds")
boosted_tuned = read_rds("data/tuned_models/boosted.rds")
```

```{r}
# Ridge
ridge_rmse = ridge_tuned %>% 
  collect_metrics() %>% 
  filter(.metric == "rmse") %>% 
  arrange(mean) %>% 
  slice(1)

# Lasso
lasso_rmse = lasso_tuned %>% 
  collect_metrics() %>% 
  filter(.metric == "rmse") %>% 
  arrange(mean) %>% 
  slice(1)

# KNN
knn_rmse = knn_tuned %>% 
  collect_metrics() %>% 
  filter(.metric == "rmse") %>% 
  arrange(mean) %>% 
  slice(1)

# Elastic Net
elastic_rmse = elastic_tuned %>% 
  collect_metrics() %>% 
  filter(.metric == "rmse") %>% 
  arrange(mean) %>% 
  slice(1)

# Random Forest
rf_rmse = rf_tuned %>% 
  collect_metrics() %>% 
  filter(.metric == "rmse") %>% 
  arrange(mean) %>% 
  slice(1)

# Boosted Trees
boosted_rmse = boosted_tuned %>% 
  collect_metrics() %>% 
  filter(.metric == "rmse") %>% 
  arrange(mean) %>% 
  slice(1)
```

Lets output it into a clean format to read. 

```{r}
rmse_summary = bind_rows(
  ridge_rmse %>% mutate(model = "Ridge Regression"),
  lasso_rmse %>% mutate(model = "Lasso Regression"),
  knn_rmse %>% mutate(model = "KNN"),
  elastic_rmse %>% mutate(model = "Elastic Net"),
  rf_rmse %>% mutate(model = "Random Forest"),
  boosted_rmse %>% mutate(model = "Boosted Trees")
) %>%
  select(model, mean, std_err)

comparison = tibble(model = c("Ridge Regression", 
                                 "Lasso Regression", 
                                 "KNN", "Elastic Net", 
                                 "Random Forest", 
                                 "Boosted Trees"),
                       
                       RMSE = c(ridge_rmse$mean, 
                                lasso_rmse$mean, 
                                knn_rmse$mean, 
                                elastic_rmse$mean, 
                                rf_rmse$mean, 
                                boosted_rmse$mean))

print(comparison)
```

A graph for the RMSE for visualization.

```{r}
ggplot(rmse_summary, aes(x = reorder(model, mean), y = mean)) +
  geom_col(fill = "lightgreen") +
  coord_flip() +
  labs(
    title = "RMSE Comparison by Model",
    x = "Model",
    y = "RMSE"
  ) +
  theme_minimal(base_size = 14)
```

```{r}
# Ridge
p_ridge = autoplot(ridge_tuned, metric = 'rmse') + ggtitle("Ridge Regression")

# Lasso
p_lasso = autoplot(lasso_tuned, metric = 'rmse') + ggtitle("Lasso Regression")

# Elastic Net
p_elastic = autoplot(elastic_tuned, metric = 'rmse') + ggtitle("Elastic Net")

# KNN
p_knn = autoplot(knn_tuned, metric = 'rmse') + ggtitle("KNN")

# Random Forest
p_rf = autoplot(rf_tuned, metric = 'rmse') + ggtitle("Random Forest")

# Boosted Trees
p_boosted = autoplot(boosted_tuned, metric = 'rmse') + ggtitle("Boosted Trees")
```

```{r}
p_knn
```

```{r, eval = FALSE}
best_knn_model = select_best(knn_tuned, metric = 'rmse')

final_workflow = finalize_workflow(knn_workflow, best_knn_model)

final_fit = fit(final_workflow, data = train_data)

write_rds(final_fit, file = "data/knn_final/knn_final_train.rds")
```

```{r}
final_fit = read_rds(file = "data/knn_final/knn_final_train.rds")

game_tibble = predict(final_fit, new_data = test_data %>%
                        select(-percent_avg_burdened))

game_tibble = bind_cols(game_tibble, test_data %>%
                          select(percent_avg_burdened))

write_rds(game_tibble, file = "data/knn_final/final_model.rds")
```

```{r}
game_tibble = read_rds(file = "data/knn_final/final_model.rds")

game_metric = metric_set(rmse)

game_tibble_metrics = game_metric(game_tibble, truth = percent_avg_burdened, estimate = .pred)

game_tibble_metrics
```

```{r, warning = FALSE}
game_tibble %>% 
  ggplot(aes(x = .pred, y = percent_avg_burdened)) +
  geom_point(alpha = 0.3) +
  xlim(0, 2) + 
  ylim(0, 2) +
  geom_abline(lty = 4) +
  coord_obs_pred() +
  labs(title = "Predicted Values vs. Actual Values")
```

```{r}
# Model: Permits ~ Jurisdiction
anova_results <- aov(percent_avg_burdened ~ total_very_low_income_cert_of_occupancy + 
                        total_low_income_cert_of_occupancy + 
                        total_moderate_income_cert_of_occupancy +
                        total_above_moderate_income_cert_of_occupancy +
                        total_cost_burden_renter +
                        total_cost_burden_owner
                      , data = train_data)

# See the summary (look for the p-value)
summary(anova_results)

```

```{r}
game_tibble = game_tibble %>%
  mutate(.resid = percent_avg_burdened - .pred) # Actual minus Predicted

# This replaces fit() and gives you the TRUE final performance
final_knn_fit = last_fit(final_workflow, split = split) 

# To save the actual model for later predictions:
final_model_obj = extract_workflow(final_knn_fit)
write_rds(final_model_obj, "data/knn_final/knn_final_model.rds")

# To get your metrics and residuals easily:
game_tibble = collect_predictions(final_knn_fit)

```

```{r}
game_tibble <- game_tibble %>%
  mutate(.resid = percent_avg_burdened - .pred)

library(ggplot2)

ggplot(game_tibble, aes(x = .pred, y = .resid)) +
  geom_point(alpha = 0.5, color = "midnightblue") +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
  geom_smooth(method = "loess", color = "blue", se = FALSE) +
  labs(title = "Residuals vs. Predicted Values",
       subtitle = "Check for patterns: A random cloud is ideal",
       x = "Predicted (percent_avg_burdened)",
       y = "Residual (Error)") +
  theme_minimal()

ggplot(game_tibble, aes(sample = .resid)) +
  stat_qq() +
  stat_qq_line(color = "red") +
  labs(title = "Normal Q-Q Plot",
       subtitle = "Points should follow the red line") +
  theme_minimal()

ggplot(game_tibble, aes(x = percent_avg_burdened, y = .pred)) +
  geom_point(alpha = 0.4) +
  geom_abline(lty = 2, color = "red") +
  labs(title = "Actual vs. Predicted",
       x = "Actual % Average Burdened",
       y = "Predicted % Average Burdened") +
  # This makes the X and Y scales identical so the 45-degree line is accurate
  coord_obs_pred() 

```

